language: ruby

rvm:
  - 2.3.3

script: bundle exec rake test:dev

branches:
  only:
    - master

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master

sudo: false # route your build to the container-based infrastructure for a faster build
