name: Ixartz's technical blog
description: Passionate about Computer Science
meta_description: "A blog where I share my little knowledge and tricks about programming"

aboutPage: true

paginate: 10
url: migration.ixartz.com
baseurl: /

google_analytics: 'UA-XXXXXXXX-X'
disqus: false
disqus_shortname: 'your-disqus-shortname'

author:         'ixartz'
authorTwitter:  'ixartz'

permalink:      /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post

gems: [jekyll-paginate]
