name: Ixartz's technical blog
shortdescription: Sharing Engineering Stuff
description: Sharing Engineering Stuff. A blog where I share my knowledge and tricks about programming and software engineering. I love testing new technologies and new tools.

aboutPage: true

paginate: 5
url: https://blog.ixartz.com
baseurl: /

logo: assets/images/avatar.png

google_analytics: 'UA-88747769-1'
disqus: true
disqus_shortname: 'ixartz'

author:         'Ixartz'
authorTwitter:  'ixartz'

permalink:      /:title/

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post
    -
        scope:
            path: ""
            type: drafts
        values:
            layout: post
    -
        scope:
            path: "*.html"
        values:
            sitemap: false

exclude: [Gemfile, Gemfile.lock, package.json, Rakefile, netlify.toml, vendor]

jekyll-minifier:
  compress_css: false
  compress_javascript: false

plugins:
  - jekyll-paginate
  - jekyll/minibundle
  - jekyll-minifier
  - jekyll-target-blank
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
